### ISSUE TITLE
nos is not working with a static function

### ISSUE THREAD

**Issue by karimkoehler** [andreaspenz/spryker-nos#8]
if you use a static function as a action nos is not able to execute the function

<button>hello-world-action="click#printHelloWorld"</button>

static printHelloWorld() {
     console.log('Hello World');
}

**Comment by athopen** [comment]
@karimkoehler Unfortunately, we do not support static methods for actions. I would advise you to switch to a normal public method or catch the events inside a `handleEvent` function.
